services:
  laravel-docker:
    container_name: laravel-docker
    build: ./
    ports:
      - 8000:80

  # vue-docker:
  #   container_name: vue-docker
  #   build: ./Cursus-spa
  #   ports:
  #     - 80:80

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel-api-players
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment: 
      PMA_HOST: mysql_db
      
