name: tuto-laravel11

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: Tests-api

    steps:
    - name: Check network connectivity
      run: |
        ping -c 4 google.com
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install Docker
      uses: hoverkraft-tech/compose-action@v2.0.1

    - name: Sleep for 10 seconds
      run: sleep 10s
      shell: bash

    - name: Database migrate
      run: docker exec laravel-docker bash -c "php artisan migrate"

    - name: Database seeding
      run: docker exec laravel-docker bash -c "php artisan db:seed"

    - name: Install Composer dependencies
      run: docker exec laravel-docker bash -c "composer install"

    - name: Run PHPUnit tests
      run: docker exec laravel-docker bash -c "php vendor/bin/phpunit"