name: tuto-laravel11

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    # - name: Copier le fichier .env
    #   run: cp ../docker/.env .env
    - name: Installer Docker
      uses: hoverkraft-tech/compose-action@v2.0.1



    - name: Dormir pendant 10 secondes
      run: sleep 10s
      shell: bash

    - name: Initialiser les conteneurs
      run: |
        for i in {1..5}; do docker-compose up -d && break || sleep 15; done

    - name: Migrer la base de données
      run: docker exec laravel-docker bash -c "php artisan migrate"

    - name: Peupler la base de données
      run: docker exec laravel-docker bash -c "php artisan db:seed"

    - name: Installer les dépendances Composer
      run: docker exec laravel-docker bash -c "composer install"

    - name: Exécuter les tests PHPUnit
      run: docker exec laravel-docker bash -c "php vendor/bin/phpunit"