name: Pinepline CI/CD

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    timeout-minutes: 120
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Installer Docker
      uses: hoverkraft-tech/compose-action@v2.0.1

    - name: Dormir pendant 10 secondes
      run: sleep 10s
      shell: bash

    - name: Initialiser les conteneurs
      run: |
        for i in {1..5}; do docker-compose up -d && break || sleep 15; done

    - name: Installer les dépendances Composer
      run: docker exec laravel-docker bash -c "composer install"

    - name: Migrer la base de données
      run: docker exec laravel-docker bash -c "php artisan migrate --force"

    - name: Peupler la base de données
      run: docker exec laravel-docker bash -c "php artisan db:seed --force"

    - name: Migrer la base de données de test
      run: docker exec laravel-docker bash -c "php artisan migrate --env=testing --force"  

    - name: Exécuter les tests PHPUnit
      run: docker exec laravel-docker bash -c "php artisan test tests/Feature"

    - name: Deploiement continue
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
      
    